version: "3.9"

services:

  mongo1:
    build:
      context: ./docker
    image: mongocustom
    container_name: mongo1
    hostname: mongo1
    networks: [mongonet]
    ports:
      - "27017:27017"
    volumes:
      - mongo1-data:/data/db
      - mongo1-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    command: --config /etc/mongod.conf
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 20

  mongo2:
    image: mongocustom
    container_name: mongo2
    hostname: mongo2
    networks: [mongonet]
    ports:
      - "27018:27017"
    volumes:
      - mongo2-data:/data/db
      - mongo2-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    command: --config /etc/mongod.conf
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 20

  mongo3:
    image: mongocustom
    container_name: mongo3
    hostname: mongo3
    networks: [mongonet]
    ports:
      - "27019:27017"
    volumes:
      - mongo3-data:/data/db
      - mongo3-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    command: --config /etc/mongod.conf
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 20

  init-replica:
    image: mongo:8.0.1
    container_name: init-replica
    networks: [mongonet]
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
    command: >
      bash -c "
        echo 'Initializing replica set...';
        mongosh --host mongo1:27017 -u admin -p adminpassword --authenticationDatabase admin --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [
              { _id: 0, host: \"mongo1:27017\" },
              { _id: 1, host: \"mongo2:27017\" },
              { _id: 2, host: \"mongo3:27017\" }
            ]
          })
        ';
        echo 'Replica set initialization DONE.';
      "

volumes:
  mongo1-data:
  mongo1-config:
  mongo2-data:
  mongo2-config:
  mongo3-data:
  mongo3-config:

networks:
  mongonet:
